/*
 * Generated by AI (GPT-5)
 * Author Name: Nisarg Raval
 */
package com.example.accountalias.web.config;

import io.swagger.v3.oas.models.ExternalDocumentation;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI openAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Account Alias API")
                        .version("v1")
                        .description("API for user registration, login, and account alias management"))
                .externalDocs(new ExternalDocumentation()
                        .description("OpenAPI 3.0 Docs")
                        .url("https://swagger.io/specification/"));
    }
}

