/*
 * Generated by AI (GPT-5)
 * Author Name: Nisarg Raval
 */
package com.example.accountalias.repository;

import com.example.accountalias.domain.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    Optional<User> findByEmail(String email);
    boolean existsByEmail(String email);
}

